// <auto-generated>
// Code generated by LUISGen TravelApp.json -cs Luis.LuisResultModel -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace TravelBot.Models
{
    public class LuisResultModel: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            HotelSearch, 
            None
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] HotelName;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public double[] number;

            // Lists
            public string[][] Hotel_Region;
            public string[][] RoomType;

            // Composites
            public class _InstanceGuestCount
            {
                public InstanceData[] number;
            }
            public class GuestCountClass
            {
                public double[] number;
                [JsonProperty("$instance")]
                public _InstanceGuestCount _instance;
            }
            public GuestCountClass[] GuestCount;

            // Instance
            public class _Instance
            {
                public InstanceData[] HotelName;
                public InstanceData[] datetime;
                public InstanceData[] number;
                public InstanceData[] Hotel_Region;
                public InstanceData[] RoomType;
                public InstanceData[] GuestCount;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<LuisResultModel>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
